version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "Asia/Bangkok"
    groups:
      runtime-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "pytest*"
          - "ruff"
          - "pdoc"
      dev-deps:
        patterns:
          - "pytest*"
          - "ruff"
          - "pdoc"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
