{% set name = "thaifin" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/thaifin-{{ version }}.tar.gz
  sha256: 6dce4056cc41789d2af30b8028b8e58bea9b6b23d1b3cf196a1d1a96e4470a4e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11,<4.0
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.11.0,<4.0.0
    - beautifulsoup4 >=4.9.1,<5.0.0
    - requests >=2.24.0,<3.0.0
    - lxml >=4.5.1,<5.0.0
    - furl >=2.1.0,<3.0.0
    - arrow >=0.16.0,<0.17.0
    - fuzzywuzzy >=0.18.0,<0.19.0
    - pandas >=1.0.5,<2.0.0
    - numpy >=1.19.5,<2.0.0
    - cachetools >=4.2.1,<5.0.0
    - tenacity >=6.3.1,<7.0.0
    - httpx >=0.27.0,<0.28.0
    - pydantic >=2.7.1,<3.0.0
  run_constrained:
    - python-Levenshtein >=0.12.0,<0.13.0

test:
  imports:
    - thaifin
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Python library for access thai stock fundamental data up to 10+ years.
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - wasdee
