{% set version = "0.2.1" %}
package:
  name: thaifin
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/CircleOnCircles/thaifin.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m poetry install

requirements:
  build:
    - python
    - setuptools
    - pip
    - poetry
  run:
    - python >= 3.8
    - pip >=20.0.2
    - beautifulsoup4
    - requests
    - lxml
    - furl
    - pydantic
    - arrow
    - fuzzywuzzy
    - python-Levenshtein
    - pandas
    - cachetools
    - tenacity

test:
  imports:
    - thaifin


about:
  home: https://github.com/CircleOnCircles/thaifin
  license: ISC
  license_file: LICENSE.md
  summary: A Python library for access thai stock fundamental data up to 10+ years.

# Build using: conda build -c conda-forge .