name: Python package to Conda
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.4
          virtualenvs-create: false
          virtualenvs-in-project: false
      - name: publish-to-conda
        uses: maxibor/conda-package-publish-action@v1.1
        with:
          subDir: 'conda'
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}